[pytest]
pythonpath = .

testpaths = tests
addopts =
     -v
     --tb=short
     --cov-report=term-missing
     --cov-report=html
     --cov=main
;     --strict-markers

;markers =
;    unit: Unit-тесты
;    integration: Integration-тесты