[pytest]
pythonpath = .

testpaths = tests
addopts =
     -v
     --tb=short
     --strict-markers
     --cov-report=term-missing
     --cov-report=html
;    --cov=src

markers =
    unit: Unit-тесты
    integration: Integration-тесты